### ISSUE TITLE
PR to General Public & Target Resources for Participants

### ISSUE THREAD

**Issue by raemacias** [codefordenver/ndoch2016#42]
Research possible e-mail addresses to send PR e-mail to.

**Comment by Mira321** [comment]
As of today (Mon 5/16) List of NDOCH PR emails sent to:

93.7 FM THE ROCK radio station (A Locally owned radio station - plays R&R from 60's thru today)
http://www.937therock.com/upcoming-events/
Janice@937therock.com

88.5 FM KGNU Radio Station (A Locally owned radio station)
http://kgnu.org/ht/calendarsonline.html
You can list event right away but they don't necessarily guarantee announcing.  They pick and chose from their calendar what to announce on the radio)

Denver Post Your Hub   (Denver Post's community news and calendar)
http://www.denverpost.com/yourhub
http://yourhub.denverpost.com/events/
(you need to have an account for this - I used mine.  You can submit but it has to go through a process of review before they post, which can take a few days)

Westword
http://www.westword.com/submit-event

Metro Denver Partners - Mentoring Youth (a non-profit)
(this is relevant because they focus on mentoring youth and community involvement)
admin@metrodenverpartners.org

Metro State University
Career Services
Campus Box 68
P.O. Box 173362
Denver, CO. 80217-3362
or deliver to Tivoli Center 900 Auraria Parkway
Emails sent to 3 staff:   http://www.msudenver.edu/career/officestaff/

In the process I located 3 places Code for Denver might want to list their volunteer opportunity:
POTENTIAL PLACES TO LIST YOUR VOLUNTEER OPPORTUNITY:

Google "Volunteer Denver" and you will see a list of web sites to advertise your volunteer position.  Some of these require an account.  I did not create an account  because I think you may want to use a Code for Denver email account if you have one.  Some examples are:

http://www.volunteermatch.org

https://www.metrovolunteers.org/

http://www.allforgood.org/

**Comment by Mira321** [comment]
Here is a sample of what I developed for an email blast.  The first
paragraph can be tweeked for the specific group receiving it.

Hello -
I am a member of Code for Denver and I wanted to invite you to an event we
think you might be interested in.  Please see the information below and
visit the links.  You do not need to be a programmer for this event - and
it is a great way to learn how programming can be used to benefit the
community.  We would love to see you there!

Code for Denver is part of Code for America, a national non-profit
organization.

_National Day of Civic Hacking - with Code for Denver_
_On Saturday June 4, 2016_, thousands of people  across the nation will
join together for National Day of Civic Hacking events. The goal of the
organization is to collaborate with residents, community groups,
non-profits, socially minded businesses and government to make their
communities stronger by providing computer programming expertise and
support.

Join us for Denver's celebration of National Day of Civic Hacking as we
focus on _housing challenges_. Most everyone is talking about the housing
challenges in Denver.  It is time to put our heads and hearts together to
create some solutions.

*All *skills levels of expertise welcome, including students!  Non
programmers also invited.  Come learn and contribute to this dynamic
creative effort in community problem solving!
http://www.meetup.com/CodeForDenver/events/230650372/
http://www.codefordenver.org/

t[image: Inline image 1]

**Comment by Mira321** [comment]
It was determined at meet-up on the 16th that it is likely there will be plenty of participation and we need to be mindful of the food budget.  At this point the efforts are more toward lining up speakers/subject matter experts.

**Comment by karenderrickdavis** [comment]
I consider them content/subject matter experts.
:)
Karen

**Comment by Mira321** [comment]
So I am trying to distinguish the two groups - genl public and entitites
that might have an interest in participating but not being the subject
matter experts.  Then there are the content area/subject matter experts/our
speakers/presenters.  I think there is another task open more directed
toward the subject matter experts.  That is why I renamed this one and made
the note I did.  Please tell me if I am confused and posting in error - I
don't want to add to confusion!  Thanks!  BTW - can you assist?  I am
having trouble with accessing the google docs - where are they again?
Thanks Karen!

**Comment by Mira321** [comment]
There are two other tasks related to this one I just noticed:  Recruit Participants, and Recruit Stakeholders.  Both are still on the In-Progress column.
